### ISSUE TITLE
Update samples to Java EE 7

### ISSUE THREAD

**Issue by arun-gupta** [wildfly-swarm/example-jaxrs#1]
Code samples should be updated to Java EE 7.

Particularly https://github.com/wildfly-swarm/example-jaxrs/blob/master/src/main/webapp/WEB-INF/web.xml is not even needed. Or should look something like https://github.com/javaee-samples/javaee7-samples/blob/master/servlet/metadata-complete/src/main/webapp/WEB-INF/web.xml.

Note the namespaces are different.

I suspect other samples are using a similar `web.xml`.

**Comment by kenfinnigan** [comment]
This issue was moved to wildfly-swarm/wildfly-swarm#24
